steps:
  
  # Initialize Terraform
  - name: 'hashicorp/terraform:1.5.0'
    id: 'init'
    entrypoint: 'terraform'
    args: ['init' ]
    
    #'-backend-config=bucket=my-terraform-state-bucket']
  
  # Validate Terraform code
  - name: 'hashicorp/terraform:1.5.0'
    id: 'validate'
    entrypoint: 'terraform'
    args: ['validate']

  # Run security scan with tfsec (or Trivy)
  - name: 'aquasec/tfsec:latest'
    id: 'security'
    args: ['.', '--soft-fail']  # Soft fail to debug issues
    # Alternative with Trivy:
    # - name: 'aquasec/trivy:latest'
    #   args: ['config', '.', '--exit-code', '0']

  # Plan Terraform changes
  - name: 'hashicorp/terraform:1.5.0'
    id: 'plan'
    entrypoint: 'terraform'
    args: ['plan', '-out=tfplan']

  # Apply changes (optional, with approval)
  - name: 'hashicorp/terraform:1.5.0'
    id: 'apply'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve', 'tfplan']
    waitFor: ['plan']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Faster execution