steps:
  # Install Terraform
 # Initialize Terraform with GCS backend
  - name: 'hashicorp/terraform:1.5.0'
    id: 'init'
    entrypoint: 'terraform'
    args: ['init', '-backend-config=bucket=my-terraform-state-bucket', '-backend-config=prefix=terraform/state']
 
  - name: 'hashicorp/terraform:1.5.0'
    id: 'validate'
    entrypoint: 'terraform'
    args: ['validate']
    
# Run security scan (fixed tfsec issue with Trivy)
  - name: 'aquasec/trivy:latest'
    id: 'security'
    args: ['config', '.', '--exit-code', '0']

    # Security scan
  - name: 'gcr.io/cloud-builders/tfsec'
    id: 'security'
    args: ['.']

    # Plan changes
  - name: 'hashicorp/terraform:1.5.0'
    id: 'plan'
    entrypoint: 'terraform'
    args: ['plan', '-out=tfplan']

    # Manual approval for prod (optional)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'approve'
    entrypoint: 'bash'
    args: ['-c', 'echo "Manual approval required for prod"']
  # Preview changes

  # Apply changes
  - name: 'hashicorp/terraform:1.5.0'
    id: 'apply'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve', 'tfplan']
options:
  logging: CLOUD_LOGGING_ONLY
