steps:
  # Install Terraform
  - name: 'hashicorp/terraform'
    id: 'init'
    entrypoint: 'terraform'
    args: ['init']
    

  # Preview changes
  - name: 'hashicorp/terraform'
    id: 'plan'
    entrypoint: 'terraform'
    args: ['plan']

  # Apply changes
  - name: 'hashicorp/terraform'
    id: 'apply'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve']

options:
  logging: CLOUD_LOGGING_ONLY
